SET 'auto.offset.reset' = 'earliest';

CREATE STREAM BBC_SUBMISSIONS WITH (kafka_topic = 'submissions') AS
SELECT ID
	,AUTHOR_FULLNAME
    ,TITLE
    ,SUBREDDIT_NAME_PREFIXED
    ,NAME
    ,AUTHOR_PREMIUM
    ,TIMESTAMPTOSTRING(CAST(CREATED AS BIGINT) * 1000, 'yyyy-MM-dd HH:mm:ss') AS CREATED_LOCAL_DATETIME
    ,URL_OVERRIDDEN_BY_DEST
    ,OVER_18
    ,SUBREDDIT_ID
    ,PERMALINK
    ,PARENT_WHITELIST_STATUS
    ,URL
    ,UPVOTE_RATIO
    ,UPS
    ,SCORE
FROM SUBMISSIONS
WHERE domain = 'bbc.co.uk'
EMIT CHANGES;