SET 'auto.offset.reset' = 'earliest';

CREATE STREAM COMMENTS
(
  ID VARCHAR KEY,
  SUBREDDIT_ID VARCHAR,
  BODY VARCHAR,
  LINK_ID VARCHAR,
  LINK_TITLE VARCHAR,
  NAME VARCHAR,
  PERMALINK VARCHAR,
  LINK_PERMALINK VARCHAR,
  LINK_AUTHOR VARCHAR,
  LINK_URL VARCHAR,
  IS_SUBMITTER BOOLEAN,
  CREATED DOUBLE,
  UPS DOUBLE
)
WITH(KAFKA_TOPIC='comments', VALUE_FORMAT='JSON')
;