SET 'auto.offset.reset' = 'earliest';

CREATE TABLE T_COMMENT_COUNTS
AS
SELECT SUBSTRING(LINK_ID,4,100) AS LINK_ID
	,COUNT(*) AS TOTAL_COMMENTS
FROM  COMMENTS
GROUP BY SUBSTRING(LINK_ID,4,100)
EMIT CHANGES
;