SET 'auto.offset.reset' = 'earliest';

CREATE TABLE T_SUBMISSIONS
(
  ID VARCHAR PRIMARY KEY,
  AUTHOR_FULLNAME VARCHAR,
  TITLE VARCHAR,
  SUBREDDIT_NAME_PREFIXED VARCHAR,
  NAME VARCHAR,
  UPVOTE_RATIO DOUBLE,
  UPS INTEGER,
  SCORE INTEGER,
  AUTHOR_PREMIUM BOOLEAN,
  CREATED DOUBLE,
  DOMAIN VARCHAR,
  URL_OVERRIDDEN_BY_DEST VARCHAR,
  OVER_18 BOOLEAN,
  SUBREDDIT_ID VARCHAR,
  PERMALINK VARCHAR,
  PARENT_WHITELIST_STATUS VARCHAR,
  URL VARCHAR,
  CREATED_UTC DOUBLE
)
WITH(KAFKA_TOPIC='submissions', VALUE_FORMAT='JSON')
;