SET 'auto.offset.reset' = 'earliest';

CREATE TABLE T_COMMENTS
(
  ID VARCHAR PRIMARY KEY,
  SUBREDDIT_ID VARCHAR,
  BODY VARCHAR,
  LINK_ID VARCHAR,
  LINK_TITLE VARCHAR,
  NAME VARCHAR,
  PERMALINK VARCHAR,
  LINK_PERMALINK VARCHAR,
  LINK_AUTHOR VARCHAR,
  LINK_URL VARCHAR,
  IS_SUBMITTER BOOLEAN,
  CREATED DOUBLE,
  UPS DOUBLE
)
WITH(KAFKA_TOPIC='comments',VALUE_FORMAT='JSON')
;