SET 'auto.offset.reset' = 'earliest';

CREATE TABLE T_SUBMISSION_COMMENTS AS
SELECT s.ID
	,s.AUTHOR_FULLNAME
    ,s.TITLE
    ,s.SUBREDDIT_NAME_PREFIXED
    ,s.NAME
    ,s.AUTHOR_PREMIUM
    ,TIMESTAMPTOSTRING(CAST(s.CREATED AS BIGINT) * 1000, 'yyyy-MM-dd HH:mm:ss') AS CREATED_LOCAL_DATETIME
    ,s.URL_OVERRIDDEN_BY_DEST
    ,s.OVER_18
    ,s.SUBREDDIT_ID
    ,s.PERMALINK
    ,s.PARENT_WHITELIST_STATUS
    ,s.URL
    ,s.UPVOTE_RATIO
    ,s.UPS
    ,s.SCORE
    ,c.TOTAL_COMMENTS
FROM  T_SUBMISSIONS s
	JOIN T_COMMENT_COUNTS  c
       ON s.ID = c.LINK_ID
EMIT CHANGES
;